// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package com.learn.service3;

public interface BMIRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BMIRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Height in centimetre.
   * </pre>
   *
   * <code>double height = 1;</code>
   */
  double getHeight();

  /**
   * <pre>
   * Weight in kilogram.
   * </pre>
   *
   * <code>double weight = 2;</code>
   */
  double getWeight();
}
