// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package com.learn.service3;

public interface BMIResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BMIResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Body Mass Index.
   * </pre>
   *
   * <code>double bmi = 1;</code>
   */
  double getBmi();

  /**
   * <pre>
   * Category based on the bmi results.
   * </pre>
   *
   * <code>string category = 2;</code>
   */
  java.lang.String getCategory();
  /**
   * <pre>
   * Category based on the bmi results.
   * </pre>
   *
   * <code>string category = 2;</code>
   */
  com.google.protobuf.ByteString
      getCategoryBytes();
}
