// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package com.learn.service3;

public final class Service3Impl {
  private Service3Impl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BMIRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BMIRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BMIResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BMIResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WeightLossWeeklyTargetRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WeightLossWeeklyTargetRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WeightLossWeeklyTargetResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WeightLossWeeklyTargetResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016service3.proto\",\n\nBMIRequest\022\016\n\006height" +
      "\030\001 \001(\001\022\016\n\006weight\030\002 \001(\001\",\n\013BMIResponse\022\013\n" +
      "\003bmi\030\001 \001(\001\022\020\n\010category\030\002 \001(\t\"a\n\035WeightLo" +
      "ssWeeklyTargetRequest\022\025\n\rcurrentWeight\030\001" +
      " \001(\001\022\022\n\nweightGoal\030\002 \001(\001\022\025\n\rnumberOfWeek" +
      "s\030\003 \001(\005\"@\n\036WeightLossWeeklyTargetRespons" +
      "e\022\036\n\026weightLossWeeklyTarget\030\001 \001(\0012\227\001\n\010Se" +
      "rvice3\022+\n\014calculateBMI\022\013.BMIRequest\032\014.BM" +
      "IResponse\"\000\022^\n\031getWeightLossWeeklyTarget" +
      "\022\036.WeightLossWeeklyTargetRequest\032\037.Weigh" +
      "tLossWeeklyTargetResponse\"\000B$\n\022com.learn" +
      ".service3B\014Service3ImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_BMIRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_BMIRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BMIRequest_descriptor,
        new java.lang.String[] { "Height", "Weight", });
    internal_static_BMIResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_BMIResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BMIResponse_descriptor,
        new java.lang.String[] { "Bmi", "Category", });
    internal_static_WeightLossWeeklyTargetRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_WeightLossWeeklyTargetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WeightLossWeeklyTargetRequest_descriptor,
        new java.lang.String[] { "CurrentWeight", "WeightGoal", "NumberOfWeeks", });
    internal_static_WeightLossWeeklyTargetResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_WeightLossWeeklyTargetResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WeightLossWeeklyTargetResponse_descriptor,
        new java.lang.String[] { "WeightLossWeeklyTarget", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
