// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package com.learn.service3;

/**
 * Protobuf type {@code WeightLossWeeklyPlanRequest}
 */
public  final class WeightLossWeeklyPlanRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:WeightLossWeeklyPlanRequest)
    WeightLossWeeklyPlanRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use WeightLossWeeklyPlanRequest.newBuilder() to construct.
  private WeightLossWeeklyPlanRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private WeightLossWeeklyPlanRequest() {
    currentWeight_ = 0D;
    weightGoal_ = 0D;
    numberOfWeeks_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private WeightLossWeeklyPlanRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 9: {

            currentWeight_ = input.readDouble();
            break;
          }
          case 17: {

            weightGoal_ = input.readDouble();
            break;
          }
          case 24: {

            numberOfWeeks_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.learn.service3.Service3Impl.internal_static_WeightLossWeeklyPlanRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.learn.service3.Service3Impl.internal_static_WeightLossWeeklyPlanRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.learn.service3.WeightLossWeeklyPlanRequest.class, com.learn.service3.WeightLossWeeklyPlanRequest.Builder.class);
  }

  public static final int CURRENTWEIGHT_FIELD_NUMBER = 1;
  private double currentWeight_;
  /**
   * <pre>
   * Current weight in kilogram.
   * </pre>
   *
   * <code>double currentWeight = 1;</code>
   */
  public double getCurrentWeight() {
    return currentWeight_;
  }

  public static final int WEIGHTGOAL_FIELD_NUMBER = 2;
  private double weightGoal_;
  /**
   * <pre>
   * Weight goal in kilogram.
   * </pre>
   *
   * <code>double weightGoal = 2;</code>
   */
  public double getWeightGoal() {
    return weightGoal_;
  }

  public static final int NUMBEROFWEEKS_FIELD_NUMBER = 3;
  private int numberOfWeeks_;
  /**
   * <pre>
   * Number of weeks for the plan.
   * </pre>
   *
   * <code>int32 numberOfWeeks = 3;</code>
   */
  public int getNumberOfWeeks() {
    return numberOfWeeks_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (currentWeight_ != 0D) {
      output.writeDouble(1, currentWeight_);
    }
    if (weightGoal_ != 0D) {
      output.writeDouble(2, weightGoal_);
    }
    if (numberOfWeeks_ != 0) {
      output.writeInt32(3, numberOfWeeks_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (currentWeight_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(1, currentWeight_);
    }
    if (weightGoal_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, weightGoal_);
    }
    if (numberOfWeeks_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, numberOfWeeks_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.learn.service3.WeightLossWeeklyPlanRequest)) {
      return super.equals(obj);
    }
    com.learn.service3.WeightLossWeeklyPlanRequest other = (com.learn.service3.WeightLossWeeklyPlanRequest) obj;

    boolean result = true;
    result = result && (
        java.lang.Double.doubleToLongBits(getCurrentWeight())
        == java.lang.Double.doubleToLongBits(
            other.getCurrentWeight()));
    result = result && (
        java.lang.Double.doubleToLongBits(getWeightGoal())
        == java.lang.Double.doubleToLongBits(
            other.getWeightGoal()));
    result = result && (getNumberOfWeeks()
        == other.getNumberOfWeeks());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CURRENTWEIGHT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getCurrentWeight()));
    hash = (37 * hash) + WEIGHTGOAL_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getWeightGoal()));
    hash = (37 * hash) + NUMBEROFWEEKS_FIELD_NUMBER;
    hash = (53 * hash) + getNumberOfWeeks();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.learn.service3.WeightLossWeeklyPlanRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.learn.service3.WeightLossWeeklyPlanRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.learn.service3.WeightLossWeeklyPlanRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.learn.service3.WeightLossWeeklyPlanRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.learn.service3.WeightLossWeeklyPlanRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.learn.service3.WeightLossWeeklyPlanRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.learn.service3.WeightLossWeeklyPlanRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.learn.service3.WeightLossWeeklyPlanRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.learn.service3.WeightLossWeeklyPlanRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.learn.service3.WeightLossWeeklyPlanRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.learn.service3.WeightLossWeeklyPlanRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.learn.service3.WeightLossWeeklyPlanRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.learn.service3.WeightLossWeeklyPlanRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code WeightLossWeeklyPlanRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:WeightLossWeeklyPlanRequest)
      com.learn.service3.WeightLossWeeklyPlanRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.learn.service3.Service3Impl.internal_static_WeightLossWeeklyPlanRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.learn.service3.Service3Impl.internal_static_WeightLossWeeklyPlanRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.learn.service3.WeightLossWeeklyPlanRequest.class, com.learn.service3.WeightLossWeeklyPlanRequest.Builder.class);
    }

    // Construct using com.learn.service3.WeightLossWeeklyPlanRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      currentWeight_ = 0D;

      weightGoal_ = 0D;

      numberOfWeeks_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.learn.service3.Service3Impl.internal_static_WeightLossWeeklyPlanRequest_descriptor;
    }

    @java.lang.Override
    public com.learn.service3.WeightLossWeeklyPlanRequest getDefaultInstanceForType() {
      return com.learn.service3.WeightLossWeeklyPlanRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.learn.service3.WeightLossWeeklyPlanRequest build() {
      com.learn.service3.WeightLossWeeklyPlanRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.learn.service3.WeightLossWeeklyPlanRequest buildPartial() {
      com.learn.service3.WeightLossWeeklyPlanRequest result = new com.learn.service3.WeightLossWeeklyPlanRequest(this);
      result.currentWeight_ = currentWeight_;
      result.weightGoal_ = weightGoal_;
      result.numberOfWeeks_ = numberOfWeeks_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.learn.service3.WeightLossWeeklyPlanRequest) {
        return mergeFrom((com.learn.service3.WeightLossWeeklyPlanRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.learn.service3.WeightLossWeeklyPlanRequest other) {
      if (other == com.learn.service3.WeightLossWeeklyPlanRequest.getDefaultInstance()) return this;
      if (other.getCurrentWeight() != 0D) {
        setCurrentWeight(other.getCurrentWeight());
      }
      if (other.getWeightGoal() != 0D) {
        setWeightGoal(other.getWeightGoal());
      }
      if (other.getNumberOfWeeks() != 0) {
        setNumberOfWeeks(other.getNumberOfWeeks());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.learn.service3.WeightLossWeeklyPlanRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.learn.service3.WeightLossWeeklyPlanRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private double currentWeight_ ;
    /**
     * <pre>
     * Current weight in kilogram.
     * </pre>
     *
     * <code>double currentWeight = 1;</code>
     */
    public double getCurrentWeight() {
      return currentWeight_;
    }
    /**
     * <pre>
     * Current weight in kilogram.
     * </pre>
     *
     * <code>double currentWeight = 1;</code>
     */
    public Builder setCurrentWeight(double value) {
      
      currentWeight_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Current weight in kilogram.
     * </pre>
     *
     * <code>double currentWeight = 1;</code>
     */
    public Builder clearCurrentWeight() {
      
      currentWeight_ = 0D;
      onChanged();
      return this;
    }

    private double weightGoal_ ;
    /**
     * <pre>
     * Weight goal in kilogram.
     * </pre>
     *
     * <code>double weightGoal = 2;</code>
     */
    public double getWeightGoal() {
      return weightGoal_;
    }
    /**
     * <pre>
     * Weight goal in kilogram.
     * </pre>
     *
     * <code>double weightGoal = 2;</code>
     */
    public Builder setWeightGoal(double value) {
      
      weightGoal_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Weight goal in kilogram.
     * </pre>
     *
     * <code>double weightGoal = 2;</code>
     */
    public Builder clearWeightGoal() {
      
      weightGoal_ = 0D;
      onChanged();
      return this;
    }

    private int numberOfWeeks_ ;
    /**
     * <pre>
     * Number of weeks for the plan.
     * </pre>
     *
     * <code>int32 numberOfWeeks = 3;</code>
     */
    public int getNumberOfWeeks() {
      return numberOfWeeks_;
    }
    /**
     * <pre>
     * Number of weeks for the plan.
     * </pre>
     *
     * <code>int32 numberOfWeeks = 3;</code>
     */
    public Builder setNumberOfWeeks(int value) {
      
      numberOfWeeks_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Number of weeks for the plan.
     * </pre>
     *
     * <code>int32 numberOfWeeks = 3;</code>
     */
    public Builder clearNumberOfWeeks() {
      
      numberOfWeeks_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:WeightLossWeeklyPlanRequest)
  }

  // @@protoc_insertion_point(class_scope:WeightLossWeeklyPlanRequest)
  private static final com.learn.service3.WeightLossWeeklyPlanRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.learn.service3.WeightLossWeeklyPlanRequest();
  }

  public static com.learn.service3.WeightLossWeeklyPlanRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<WeightLossWeeklyPlanRequest>
      PARSER = new com.google.protobuf.AbstractParser<WeightLossWeeklyPlanRequest>() {
    @java.lang.Override
    public WeightLossWeeklyPlanRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new WeightLossWeeklyPlanRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<WeightLossWeeklyPlanRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<WeightLossWeeklyPlanRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.learn.service3.WeightLossWeeklyPlanRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

