// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package com.learn.service3;

public interface WeightLossWeeklyPlanResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:WeightLossWeeklyPlanResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Week number for the plan.
   * </pre>
   *
   * <code>int32 weekNumber = 1;</code>
   */
  int getWeekNumber();

  /**
   * <pre>
   * Weight loss goal for the week in kilogram.
   * </pre>
   *
   * <code>double weightLossGoal = 2;</code>
   */
  double getWeightLossGoal();
}
