// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package com.learn.service3;

/**
 * Protobuf type {@code WeightLossWeeklyPlanResponse}
 */
public  final class WeightLossWeeklyPlanResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:WeightLossWeeklyPlanResponse)
    WeightLossWeeklyPlanResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use WeightLossWeeklyPlanResponse.newBuilder() to construct.
  private WeightLossWeeklyPlanResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private WeightLossWeeklyPlanResponse() {
    weekNumber_ = 0;
    weightLossGoal_ = 0D;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private WeightLossWeeklyPlanResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            weekNumber_ = input.readInt32();
            break;
          }
          case 17: {

            weightLossGoal_ = input.readDouble();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.learn.service3.Service3Impl.internal_static_WeightLossWeeklyPlanResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.learn.service3.Service3Impl.internal_static_WeightLossWeeklyPlanResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.learn.service3.WeightLossWeeklyPlanResponse.class, com.learn.service3.WeightLossWeeklyPlanResponse.Builder.class);
  }

  public static final int WEEKNUMBER_FIELD_NUMBER = 1;
  private int weekNumber_;
  /**
   * <pre>
   * Week number for the plan.
   * </pre>
   *
   * <code>int32 weekNumber = 1;</code>
   */
  public int getWeekNumber() {
    return weekNumber_;
  }

  public static final int WEIGHTLOSSGOAL_FIELD_NUMBER = 2;
  private double weightLossGoal_;
  /**
   * <pre>
   * Weight loss goal for the week in kilogram.
   * </pre>
   *
   * <code>double weightLossGoal = 2;</code>
   */
  public double getWeightLossGoal() {
    return weightLossGoal_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (weekNumber_ != 0) {
      output.writeInt32(1, weekNumber_);
    }
    if (weightLossGoal_ != 0D) {
      output.writeDouble(2, weightLossGoal_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (weekNumber_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, weekNumber_);
    }
    if (weightLossGoal_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, weightLossGoal_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.learn.service3.WeightLossWeeklyPlanResponse)) {
      return super.equals(obj);
    }
    com.learn.service3.WeightLossWeeklyPlanResponse other = (com.learn.service3.WeightLossWeeklyPlanResponse) obj;

    boolean result = true;
    result = result && (getWeekNumber()
        == other.getWeekNumber());
    result = result && (
        java.lang.Double.doubleToLongBits(getWeightLossGoal())
        == java.lang.Double.doubleToLongBits(
            other.getWeightLossGoal()));
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + WEEKNUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getWeekNumber();
    hash = (37 * hash) + WEIGHTLOSSGOAL_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getWeightLossGoal()));
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.learn.service3.WeightLossWeeklyPlanResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.learn.service3.WeightLossWeeklyPlanResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.learn.service3.WeightLossWeeklyPlanResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.learn.service3.WeightLossWeeklyPlanResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.learn.service3.WeightLossWeeklyPlanResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.learn.service3.WeightLossWeeklyPlanResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.learn.service3.WeightLossWeeklyPlanResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.learn.service3.WeightLossWeeklyPlanResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.learn.service3.WeightLossWeeklyPlanResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.learn.service3.WeightLossWeeklyPlanResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.learn.service3.WeightLossWeeklyPlanResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.learn.service3.WeightLossWeeklyPlanResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.learn.service3.WeightLossWeeklyPlanResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code WeightLossWeeklyPlanResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:WeightLossWeeklyPlanResponse)
      com.learn.service3.WeightLossWeeklyPlanResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.learn.service3.Service3Impl.internal_static_WeightLossWeeklyPlanResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.learn.service3.Service3Impl.internal_static_WeightLossWeeklyPlanResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.learn.service3.WeightLossWeeklyPlanResponse.class, com.learn.service3.WeightLossWeeklyPlanResponse.Builder.class);
    }

    // Construct using com.learn.service3.WeightLossWeeklyPlanResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      weekNumber_ = 0;

      weightLossGoal_ = 0D;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.learn.service3.Service3Impl.internal_static_WeightLossWeeklyPlanResponse_descriptor;
    }

    @java.lang.Override
    public com.learn.service3.WeightLossWeeklyPlanResponse getDefaultInstanceForType() {
      return com.learn.service3.WeightLossWeeklyPlanResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.learn.service3.WeightLossWeeklyPlanResponse build() {
      com.learn.service3.WeightLossWeeklyPlanResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.learn.service3.WeightLossWeeklyPlanResponse buildPartial() {
      com.learn.service3.WeightLossWeeklyPlanResponse result = new com.learn.service3.WeightLossWeeklyPlanResponse(this);
      result.weekNumber_ = weekNumber_;
      result.weightLossGoal_ = weightLossGoal_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.learn.service3.WeightLossWeeklyPlanResponse) {
        return mergeFrom((com.learn.service3.WeightLossWeeklyPlanResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.learn.service3.WeightLossWeeklyPlanResponse other) {
      if (other == com.learn.service3.WeightLossWeeklyPlanResponse.getDefaultInstance()) return this;
      if (other.getWeekNumber() != 0) {
        setWeekNumber(other.getWeekNumber());
      }
      if (other.getWeightLossGoal() != 0D) {
        setWeightLossGoal(other.getWeightLossGoal());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.learn.service3.WeightLossWeeklyPlanResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.learn.service3.WeightLossWeeklyPlanResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int weekNumber_ ;
    /**
     * <pre>
     * Week number for the plan.
     * </pre>
     *
     * <code>int32 weekNumber = 1;</code>
     */
    public int getWeekNumber() {
      return weekNumber_;
    }
    /**
     * <pre>
     * Week number for the plan.
     * </pre>
     *
     * <code>int32 weekNumber = 1;</code>
     */
    public Builder setWeekNumber(int value) {
      
      weekNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Week number for the plan.
     * </pre>
     *
     * <code>int32 weekNumber = 1;</code>
     */
    public Builder clearWeekNumber() {
      
      weekNumber_ = 0;
      onChanged();
      return this;
    }

    private double weightLossGoal_ ;
    /**
     * <pre>
     * Weight loss goal for the week in kilogram.
     * </pre>
     *
     * <code>double weightLossGoal = 2;</code>
     */
    public double getWeightLossGoal() {
      return weightLossGoal_;
    }
    /**
     * <pre>
     * Weight loss goal for the week in kilogram.
     * </pre>
     *
     * <code>double weightLossGoal = 2;</code>
     */
    public Builder setWeightLossGoal(double value) {
      
      weightLossGoal_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Weight loss goal for the week in kilogram.
     * </pre>
     *
     * <code>double weightLossGoal = 2;</code>
     */
    public Builder clearWeightLossGoal() {
      
      weightLossGoal_ = 0D;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:WeightLossWeeklyPlanResponse)
  }

  // @@protoc_insertion_point(class_scope:WeightLossWeeklyPlanResponse)
  private static final com.learn.service3.WeightLossWeeklyPlanResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.learn.service3.WeightLossWeeklyPlanResponse();
  }

  public static com.learn.service3.WeightLossWeeklyPlanResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<WeightLossWeeklyPlanResponse>
      PARSER = new com.google.protobuf.AbstractParser<WeightLossWeeklyPlanResponse>() {
    @java.lang.Override
    public WeightLossWeeklyPlanResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new WeightLossWeeklyPlanResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<WeightLossWeeklyPlanResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<WeightLossWeeklyPlanResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.learn.service3.WeightLossWeeklyPlanResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

