// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package com.learn.service3;

/**
 * Protobuf type {@code WeightLossWeeklyTargetResponse}
 */
public  final class WeightLossWeeklyTargetResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:WeightLossWeeklyTargetResponse)
    WeightLossWeeklyTargetResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use WeightLossWeeklyTargetResponse.newBuilder() to construct.
  private WeightLossWeeklyTargetResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private WeightLossWeeklyTargetResponse() {
    weightLossWeeklyTarget_ = 0D;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private WeightLossWeeklyTargetResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 9: {

            weightLossWeeklyTarget_ = input.readDouble();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.learn.service3.Service3Impl.internal_static_WeightLossWeeklyTargetResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.learn.service3.Service3Impl.internal_static_WeightLossWeeklyTargetResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.learn.service3.WeightLossWeeklyTargetResponse.class, com.learn.service3.WeightLossWeeklyTargetResponse.Builder.class);
  }

  public static final int WEIGHTLOSSWEEKLYTARGET_FIELD_NUMBER = 1;
  private double weightLossWeeklyTarget_;
  /**
   * <pre>
   * Weight loss weekly target in kilogram.
   * </pre>
   *
   * <code>double weightLossWeeklyTarget = 1;</code>
   */
  public double getWeightLossWeeklyTarget() {
    return weightLossWeeklyTarget_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (weightLossWeeklyTarget_ != 0D) {
      output.writeDouble(1, weightLossWeeklyTarget_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (weightLossWeeklyTarget_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(1, weightLossWeeklyTarget_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.learn.service3.WeightLossWeeklyTargetResponse)) {
      return super.equals(obj);
    }
    com.learn.service3.WeightLossWeeklyTargetResponse other = (com.learn.service3.WeightLossWeeklyTargetResponse) obj;

    boolean result = true;
    result = result && (
        java.lang.Double.doubleToLongBits(getWeightLossWeeklyTarget())
        == java.lang.Double.doubleToLongBits(
            other.getWeightLossWeeklyTarget()));
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + WEIGHTLOSSWEEKLYTARGET_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getWeightLossWeeklyTarget()));
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.learn.service3.WeightLossWeeklyTargetResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.learn.service3.WeightLossWeeklyTargetResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.learn.service3.WeightLossWeeklyTargetResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.learn.service3.WeightLossWeeklyTargetResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.learn.service3.WeightLossWeeklyTargetResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.learn.service3.WeightLossWeeklyTargetResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.learn.service3.WeightLossWeeklyTargetResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.learn.service3.WeightLossWeeklyTargetResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.learn.service3.WeightLossWeeklyTargetResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.learn.service3.WeightLossWeeklyTargetResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.learn.service3.WeightLossWeeklyTargetResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.learn.service3.WeightLossWeeklyTargetResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.learn.service3.WeightLossWeeklyTargetResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code WeightLossWeeklyTargetResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:WeightLossWeeklyTargetResponse)
      com.learn.service3.WeightLossWeeklyTargetResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.learn.service3.Service3Impl.internal_static_WeightLossWeeklyTargetResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.learn.service3.Service3Impl.internal_static_WeightLossWeeklyTargetResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.learn.service3.WeightLossWeeklyTargetResponse.class, com.learn.service3.WeightLossWeeklyTargetResponse.Builder.class);
    }

    // Construct using com.learn.service3.WeightLossWeeklyTargetResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      weightLossWeeklyTarget_ = 0D;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.learn.service3.Service3Impl.internal_static_WeightLossWeeklyTargetResponse_descriptor;
    }

    @java.lang.Override
    public com.learn.service3.WeightLossWeeklyTargetResponse getDefaultInstanceForType() {
      return com.learn.service3.WeightLossWeeklyTargetResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.learn.service3.WeightLossWeeklyTargetResponse build() {
      com.learn.service3.WeightLossWeeklyTargetResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.learn.service3.WeightLossWeeklyTargetResponse buildPartial() {
      com.learn.service3.WeightLossWeeklyTargetResponse result = new com.learn.service3.WeightLossWeeklyTargetResponse(this);
      result.weightLossWeeklyTarget_ = weightLossWeeklyTarget_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.learn.service3.WeightLossWeeklyTargetResponse) {
        return mergeFrom((com.learn.service3.WeightLossWeeklyTargetResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.learn.service3.WeightLossWeeklyTargetResponse other) {
      if (other == com.learn.service3.WeightLossWeeklyTargetResponse.getDefaultInstance()) return this;
      if (other.getWeightLossWeeklyTarget() != 0D) {
        setWeightLossWeeklyTarget(other.getWeightLossWeeklyTarget());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.learn.service3.WeightLossWeeklyTargetResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.learn.service3.WeightLossWeeklyTargetResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private double weightLossWeeklyTarget_ ;
    /**
     * <pre>
     * Weight loss weekly target in kilogram.
     * </pre>
     *
     * <code>double weightLossWeeklyTarget = 1;</code>
     */
    public double getWeightLossWeeklyTarget() {
      return weightLossWeeklyTarget_;
    }
    /**
     * <pre>
     * Weight loss weekly target in kilogram.
     * </pre>
     *
     * <code>double weightLossWeeklyTarget = 1;</code>
     */
    public Builder setWeightLossWeeklyTarget(double value) {
      
      weightLossWeeklyTarget_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Weight loss weekly target in kilogram.
     * </pre>
     *
     * <code>double weightLossWeeklyTarget = 1;</code>
     */
    public Builder clearWeightLossWeeklyTarget() {
      
      weightLossWeeklyTarget_ = 0D;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:WeightLossWeeklyTargetResponse)
  }

  // @@protoc_insertion_point(class_scope:WeightLossWeeklyTargetResponse)
  private static final com.learn.service3.WeightLossWeeklyTargetResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.learn.service3.WeightLossWeeklyTargetResponse();
  }

  public static com.learn.service3.WeightLossWeeklyTargetResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<WeightLossWeeklyTargetResponse>
      PARSER = new com.google.protobuf.AbstractParser<WeightLossWeeklyTargetResponse>() {
    @java.lang.Override
    public WeightLossWeeklyTargetResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new WeightLossWeeklyTargetResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<WeightLossWeeklyTargetResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<WeightLossWeeklyTargetResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.learn.service3.WeightLossWeeklyTargetResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

