// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package com.learn.service3;

public interface WeightLossWeeklyTargetResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:WeightLossWeeklyTargetResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Weight loss weekly target in kilogram.
   * </pre>
   *
   * <code>double weightLossWeeklyTarget = 1;</code>
   */
  double getWeightLossWeeklyTarget();
}
