// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package com.learn.service1;

public interface GetUserProfileRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetUserProfileRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * User's username.
   * </pre>
   *
   * <code>string username = 1;</code>
   */
  java.lang.String getUsername();
  /**
   * <pre>
   * User's username.
   * </pre>
   *
   * <code>string username = 1;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();
}
