// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package com.learn.service1;

public interface GetUserProfileRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetUserProfileRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * User identifier.
   * </pre>
   *
   * <code>int64 userId = 1;</code>
   */
  long getUserId();
}
