// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package com.learn.service1;

public interface GetUserProfileResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetUserProfileResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * User's name.
   * </pre>
   *
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <pre>
   * User's name.
   * </pre>
   *
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * User's height in centimetre.
   * </pre>
   *
   * <code>double height = 2;</code>
   */
  double getHeight();

  /**
   * <pre>
   * User's weight in kilogram.
   * </pre>
   *
   * <code>double weight = 3;</code>
   */
  double getWeight();

  /**
   * <pre>
   * User's daily step count goal.
   * </pre>
   *
   * <code>int32 stepCountGoal = 4;</code>
   */
  int getStepCountGoal();

  /**
   * <pre>
   * User's weight goal in kilogram.
   * </pre>
   *
   * <code>double weightGoal = 5;</code>
   */
  double getWeightGoal();
}
