// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package com.learn.service1;

public interface SetUserProfileResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SetUserProfileResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Response message.
   * </pre>
   *
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <pre>
   * Response message.
   * </pre>
   *
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
