// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package com.learn.sample;

public final class SampleServiceImpl {
  private SampleServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UnaryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UnaryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UnaryResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UnaryResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ServerStreamRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ServerStreamRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ServerStreamResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ServerStreamResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClientStreamRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ClientStreamRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClientStreamResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ClientStreamResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BidirectionalStreamRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BidirectionalStreamRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BidirectionalStreamResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BidirectionalStreamResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016service1.proto\"\037\n\014UnaryRequest\022\017\n\007mess" +
      "age\030\001 \001(\t\" \n\rUnaryResponse\022\017\n\007message\030\001 " +
      "\001(\t\"&\n\023ServerStreamRequest\022\017\n\007message\030\001 " +
      "\001(\t\"\'\n\024ServerStreamResponse\022\017\n\007message\030\001" +
      " \001(\t\"&\n\023ClientStreamRequest\022\017\n\007message\030\001" +
      " \001(\t\"\'\n\024ClientStreamResponse\022\017\n\007message\030" +
      "\001 \001(\t\"-\n\032BidirectionalStreamRequest\022\017\n\007m" +
      "essage\030\001 \001(\t\".\n\033BidirectionalStreamRespo" +
      "nse\022\017\n\007message\030\001 \001(\t2\223\002\n\rSampleService\022(" +
      "\n\005unary\022\r.UnaryRequest\032\016.UnaryResponse\"\000" +
      "\022?\n\014serverStream\022\024.ServerStreamRequest\032\025" +
      ".ServerStreamResponse\"\0000\001\022?\n\014clientStrea" +
      "m\022\024.ClientStreamRequest\032\025.ClientStreamRe" +
      "sponse\"\000(\001\022V\n\023bidirectionalStream\022\033.Bidi" +
      "rectionalStreamRequest\032\034.BidirectionalSt" +
      "reamResponse\"\000(\0010\001B\'\n\020com.learn.sampleB\021" +
      "SampleServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_UnaryRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_UnaryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UnaryRequest_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_UnaryResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_UnaryResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UnaryResponse_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_ServerStreamRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ServerStreamRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ServerStreamRequest_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_ServerStreamResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ServerStreamResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ServerStreamResponse_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_ClientStreamRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_ClientStreamRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ClientStreamRequest_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_ClientStreamResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_ClientStreamResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ClientStreamResponse_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_BidirectionalStreamRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_BidirectionalStreamRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BidirectionalStreamRequest_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_BidirectionalStreamResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_BidirectionalStreamResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BidirectionalStreamResponse_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
