// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package com.learn.sample;

public interface UnaryResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UnaryResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
