// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sampleService.proto

package com.learn.sample;

public interface UnaryRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UnaryRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
