// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package com.learn.service2;

public final class Service2Impl {
  private Service2Impl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StepCountRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StepCountRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StepCountResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StepCountResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StepCountHistoryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StepCountHistoryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StepCountHistoryResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StepCountHistoryResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StepCountAverageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StepCountAverageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StepCountAverageResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StepCountAverageResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016service2.proto\"$\n\020StepCountRequest\022\020\n\010" +
      "username\030\001 \001(\t\"&\n\021StepCountResponse\022\021\n\ts" +
      "tepCount\030\001 \001(\005\"+\n\027StepCountHistoryReques" +
      "t\022\020\n\010username\030\001 \001(\t\";\n\030StepCountHistoryR" +
      "esponse\022\014\n\004date\030\001 \001(\t\022\021\n\tstepCount\030\002 \001(\005" +
      "\",\n\027StepCountAverageRequest\022\021\n\tstepCount" +
      "\030\001 \001(\005\"4\n\030StepCountAverageResponse\022\030\n\020av" +
      "erageStepCount\030\001 \001(\0052\363\001\n\010Service2\022A\n\022inc" +
      "rementStepCount\022\021.StepCountRequest\032\022.Ste" +
      "pCountResponse\"\000(\0010\001\022N\n\023getStepCountHist" +
      "ory\022\030.StepCountHistoryRequest\032\031.StepCoun" +
      "tHistoryResponse\"\0000\001\022T\n\031calculateStepCou" +
      "ntAverage\022\030.StepCountAverageRequest\032\031.St" +
      "epCountAverageResponse\"\000(\001B$\n\022com.learn." +
      "service2B\014Service2ImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_StepCountRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_StepCountRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StepCountRequest_descriptor,
        new java.lang.String[] { "Username", });
    internal_static_StepCountResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_StepCountResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StepCountResponse_descriptor,
        new java.lang.String[] { "StepCount", });
    internal_static_StepCountHistoryRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_StepCountHistoryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StepCountHistoryRequest_descriptor,
        new java.lang.String[] { "Username", });
    internal_static_StepCountHistoryResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_StepCountHistoryResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StepCountHistoryResponse_descriptor,
        new java.lang.String[] { "Date", "StepCount", });
    internal_static_StepCountAverageRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_StepCountAverageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StepCountAverageRequest_descriptor,
        new java.lang.String[] { "StepCount", });
    internal_static_StepCountAverageResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_StepCountAverageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StepCountAverageResponse_descriptor,
        new java.lang.String[] { "AverageStepCount", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
