// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package com.learn.service2;

public interface StepCountAverageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:StepCountAverageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Step count for a day.
   * </pre>
   *
   * <code>int32 stepCount = 1;</code>
   */
  int getStepCount();
}
