// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package com.learn.service2;

public interface StepCountRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:StepCountRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * User's username.
   * </pre>
   *
   * <code>string username = 1;</code>
   */
  java.lang.String getUsername();
  /**
   * <pre>
   * User's username.
   * </pre>
   *
   * <code>string username = 1;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <pre>
   * Number of steps to increment for the current date.
   * </pre>
   *
   * <code>int32 numberOfSteps = 2;</code>
   */
  int getNumberOfSteps();
}
