// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package com.learn.service2;

public interface StepCountRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:StepCountRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * User's identifier.
   * </pre>
   *
   * <code>int64 userId = 1;</code>
   */
  long getUserId();

  /**
   * <pre>
   * Number of steps to increment for the current date.
   * </pre>
   *
   * <code>int32 numberOfSteps = 2;</code>
   */
  int getNumberOfSteps();
}
