// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package com.learn.service2;

public interface StepCountHistoryResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:StepCountHistoryResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * History date.
   * </pre>
   *
   * <code>string date = 1;</code>
   */
  java.lang.String getDate();
  /**
   * <pre>
   * History date.
   * </pre>
   *
   * <code>string date = 1;</code>
   */
  com.google.protobuf.ByteString
      getDateBytes();

  /**
   * <pre>
   * Total number of steps.
   * </pre>
   *
   * <code>int32 stepCount = 2;</code>
   */
  int getStepCount();
}
