// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package com.learn.service2;

public interface StepCountHistoryRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:StepCountHistoryRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * User's identifier.
   * </pre>
   *
   * <code>int64 userId = 1;</code>
   */
  long getUserId();
}
