// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package com.learn.service2;

public interface StepCountAverageResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:StepCountAverageResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Average step count.
   * </pre>
   *
   * <code>int32 averageStepCount = 1;</code>
   */
  int getAverageStepCount();
}
