// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package com.learn.service2;

public interface StepCountResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:StepCountResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Total number of steps for the current date.
   * </pre>
   *
   * <code>int32 stepCount = 1;</code>
   */
  int getStepCount();
}
